

Resources:
  # IAM Role for EMR serverless
  EMRServerlessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: role-emr-serverless-sample
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - emr-serverless.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: 'EMRServerlessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 
                  - 's3:*'
                  - 'logs:*'
                Resource: '*'
              # This part is needed if we want to interact with Glue Data Catalog (e.g. in Hive Job)  
              # - Effect: Allow
              #   Action:
              #     - "glue:GetDatabase"
              #     - "glue:CreateDatabase"
              #     - "glue:GetDatabases"
              #     - "glue:CreateTable"
              #     - "glue:GetTable"
              #     - "glue:UpdateTable"
              #     - "glue:DeleteTable"
              #     - "glue:GetTables"
              #     - "glue:GetPartition"
              #     - "glue:GetPartitions"
              #     - "glue:CreatePartition"
              #     - "glue:BatchCreatePartition"
              #     - "glue:GetUserDefinedFunctions"
                Resource: "*"                

  # S3 bucket for EMR scripts
  EMRServerlessS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "s3-emr-serverless-demo-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  EMRServerlessApplication:
    Type: 'AWS::EMRServerless::Application'
    Properties:
      Name: emrsrvless-app-sample
      ReleaseLabel: emr-6.15.0
      Type: Spark
      AutoStartConfiguration:
        Enabled: true
      AutoStopConfiguration:
        Enabled: true
        IdleTimeoutMinutes: 15
      MaximumCapacity:
        Cpu: '40 vCPU'
        Memory: '3000 GB'
        Disk: '20000 GB'

Outputs:
  EMRServerlessApplicationId:
    Value: !Ref EMRServerlessApplication
    Export:
      Name: EMRServerlessApplicationId

  EMRServerlessRoleArn:
    Value: !GetAtt EMRServerlessRole.Arn
    Export:
      Name: EMRServerlessRoleArn

  EMRServerlessS3Bucket:
    Value: !Ref EMRServerlessS3Bucket
    Export:
      Name: EMRServerlessS3Bucket