name: Second Demo
run-name: running second demo -> ${{ github.actor }}
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The 777 job was automatically triggered by a ${{ github.event_name }} event."
