
Parameters:
  ProjectName:
    Description: ProjectName used also as Airflow EnvironmentName and used in Tags
    Type: String

  MWAAS3Bucket:
    Description: S3 bucket name for Airflow
    Type: String

  MWAASecurityGroupIds:
    Description: CSV List of Security Groups
    Type: CommaDelimitedList

  MWAASubnetIds:
    Description: CSV List of  Subnets
    Type: CommaDelimitedList

#####################################
Resources:
  AirflowIAMRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub 'iamr-${ProjectName}-mwaa'
      Description: "IAM role for MWAA environment"
      AssumeRolePolicyDocument: 
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - airflow.amazonaws.com
            - airflow-env.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyName: 'iamp-mwaa-s3'
          PolicyDocument:
            Statement:
              - Action:
                  - s3:*
                Effect: Allow
                Resource:
                - !Sub 'arn:aws:s3:::s3-${ProjectName}-${AWS::AccountId}'
                - !Sub 'arn:aws:s3:::s3-${ProjectName}-${AWS::AccountId}/*'
            Version: '2012-10-17'
        - PolicyName: 'iamp-mwaa-execution-policy'
          PolicyDocument:
            Statement:
            - Action: airflow:PublishMetrics
              Effect: Allow
              Resource: !Sub 'arn:aws:airflow:${AWS::Region}:${AWS::AccountId}:environment/${ProjectName}'
            - Action:
              - logs:CreateLogStream
              - logs:CreateLogGroup
              - logs:PutLogEvents
              - logs:GetLogEvents
              - logs:GetLogRecord
              - logs:GetLogGroupFields
              - logs:GetQueryResults
              Effect: Allow
              Resource:
              - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:airflow-${ProjectName}-*'
            - Action:
              - logs:DescribeLogGroups
              Effect: Allow
              Resource:
              - '*'
            - Action: cloudwatch:PutMetricData
              Effect: Allow
              Resource: '*'
            - Action:
              - sqs:ChangeMessageVisibility
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
              - sqs:SendMessage
              Effect: Allow
              Resource: !Sub 'arn:aws:sqs:${AWS::Region}:*:airflow-celery-*'
            - Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:GenerateDataKey*
              - kms:Encrypt
              Condition:
                StringLike:
                  kms:ViaService:
                  - !Sub 'sqs.${AWS::Region}.amazonaws.com'
              Effect: Allow
              NotResource: !Sub 'arn:aws:kms:*:${AWS::AccountId}:key/*'
            Version: '2012-10-17' 
        - PolicyName: 'iamp-mwaa-mwaaenv'
          PolicyDocument:
            Statement:
            - Action: airflow:GetEnvironment
              Effect: Allow
              Resource: !Sub 'arn:aws:airflow:${AWS::Region}:${AWS::AccountId}:environment/${ProjectName}'
        - PolicyName: 'iamp-mwaa-secrets'
          PolicyDocument:
            Statement:
            - Action: 
              - secretsmanager:GetResourcePolicy
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
              - secretsmanager:ListSecretVersionIds
              Effect: Allow
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*'
            - Action: 
              - secretsmanager:ListSecrets
              Effect: Allow
              Resource: '*'

  AirflowEnv:
    Type: AWS::MWAA::Environment
    Properties:
      AirflowVersion: 2.5.1
      DagS3Path: dags
      EnvironmentClass: mw1.small
      MaxWorkers: 2
      MinWorkers: 1
      Name: !Ref ProjectName
      NetworkConfiguration:
        SecurityGroupIds: !Ref MWAASecurityGroupIds
        SubnetIds: !Ref MWAASubnetIds        
      Schedulers: 2
      SourceBucketArn: !Sub 'arn:aws:s3:::${MWAAS3Bucket}'
      ExecutionRoleArn: !GetAtt AirflowIAMRole.Arn
      RequirementsS3Path: requirements.txt
      AirflowConfigurationOptions:
        secrets.backend: airflow.providers.amazon.aws.secrets.secrets_manager.SecretsManagerBackend
        secrets.backend_kwargs: !Sub '{"connections_prefix" : "${ProjectName}/connections", "variables_prefix" : "${ProjectName}/variables"}'
        os_var.variable1: value1
        env.variable2: 2023
      LoggingConfiguration:
        DagProcessingLogs:
          Enabled: true
          LogLevel: INFO
        SchedulerLogs:
          Enabled: true
          LogLevel: INFO
        TaskLogs:
          Enabled: true
          LogLevel: INFO
        WebserverLogs:
          Enabled: true
          LogLevel: INFO
        WorkerLogs:
          Enabled: true
          LogLevel: INFO
      WebserverAccessMode: PUBLIC_ONLY
      WeeklyMaintenanceWindowStart: SUN:21:00
