

Parameters:
  ProjectName:
    Description: An project name that is prefixed to resource names
    Type: String

  DBHost:
    Description: Database host
    Type: String  

  DBLogin:
    Description: Database username
    Type: String      

  DBPassword:
    Description: Database password
    Type: String          
    NoEcho: true

  DBDatabase:
    Description: Database to connect to
    Type: String          

Resources:
  SecretAuroraMySQLURI:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/connections/aurora_mysql_uri'
      SecretString: !Sub 'mysql://${DBLogin}:${DBPassword}@${DBHost}:3306/${DBDatabase}'

  SecretAuroraMySQLJSON:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/connections/aurora_mysql_json'
      SecretString: !Sub |
        {
            "conn_type": "mysql",
            "login": "${DBLogin}",
            "password": "${DBPassword}",
            "host": "${DBHost}",
            "database": "${DBDatabase}",
            "port": 3306
        }

  SecretMWAATestVariable:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/variables/test_variable'
      SecretString: This is a Value of test variable (stored in secrets manager)
