

Parameters:
  ProjectName:
    Description: An project name that is prefixed to resource names
    Type: String

Resources:
  SecretAuroraMySQLURI:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/connections/aurora_mysql_uri'
      SecretString: mysql://auroraadmin:MyPassword123@auroradbclustermysql.cluster-cc35n7kktpm5.eu-central-1.rds.amazonaws.com:3306/mydatabase

  # https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html
  # Starting from ver 2.3.0
  SecretAuroraMySQLJSON:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/connections/aurora_mysql_json'
      SecretString: |
        {
            "conn_type": "mysql",
            "login": "auroraadmin",
            "password": "MyPassword123",
            "host": "auroradbclustermysql.cluster-cc35n7kktpm5.eu-central-1.rds.amazonaws.com",
            "database": "mydatabase",
            "port": 3306
        }

  SecretMWAATestVariable:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/variables/test_variable'
      SecretString: This is a Value of test variable (stored in secrets manager)
