

Parameters:
  ProjectName:
    Description: An project name that is prefixed to resource names
    Type: String


Resources:
  SecretAuroraPostgreSQLURI:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/connections/aurora_postgresql_uri'
      SecretString: postgres://auroraadmin:MyPassword123@myauroradbcluster.cluster-cc35n7kktpm5.eu-central-1.rds.amazonaws.com:5432/mydatabase

  # https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html
  # Starting from ver 2.3.0
  SecretAuroraPostgreSQLJSON:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/connections/aurora_postgresql_json'
      SecretString: |
        {
            "conn_type": "postgres",
            "login": "auroraadmin",
            "password": "MyPassword123",
            "host": "myauroradbcluster.cluster-cc35n7kktpm5.eu-central-1.rds.amazonaws.com",
            "database": "mydatabase",
            "port": 5432
        }        

