

Parameters:
  ProjectName:
    Description: An project name that is prefixed to resource names
    Type: String

  DBHost:
    Description: Database host
    Type: String  

  DBLogin:
    Description: Database username
    Type: String      

  DBPassword:
    Description: Database password
    Type: String          
    NoEcho: true

  DBDatabase:
    Description: Database to connect to
    Type: String    

Resources:
  SecretAuroraPostgreSQLURI:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/connections/aurora_postgresql_uri'      
      SecretString: !Sub 'postgres://${DBLogin}:${DBPassword}@${DBHost}:5432/${DBDatabase}'

  SecretAuroraPostgreSQLJSON:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/connections/aurora_postgresql_json'
      SecretString: !Sub |
        {
            "conn_type": "postgres",
            "login": "${DBLogin}",
            "password": "${DBPassword}",
            "host": "${DBHost}",
            "database": "${DBDatabase}",
            "port": 5432
        }      
     

