AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EMRServerlessS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "s3-emr-serverless-tutorial-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  MyIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: role-EMRNotebook-tutorial
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Sid: ""
            Effect: Allow
            Principal:
              Service: elasticmapreduce.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceEditorsRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Path: "/"
      Description: 'Role for EMR with S3 Full Access'

  EMRServerlessExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: role-EMRServerlessExecutionRole-tutorial
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: emr-serverless.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: EMRServerlessExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: "ReadAccessForEMRSamples"
                Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource:
                  - "arn:aws:s3:::*.elasticmapreduce"
                  - "arn:aws:s3:::*.elasticmapreduce/*"
              - Sid: "FullAccessToOutputBucket"
                Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                  - "s3:DeleteObject"
                Resource:
                  - "arn:aws:s3:::*"
                  - "arn:aws:s3:::*/*"
              - Sid: "GlueCreateAndReadDataCatalog"
                Effect: Allow
                Action:
                  - "glue:GetDatabase"
                  - "glue:CreateDatabase"
                  - "glue:GetDatabases"
                  - "glue:CreateTable"
                  - "glue:GetTable"
                  - "glue:UpdateTable"
                  - "glue:DeleteTable"
                  - "glue:GetTables"
                  - "glue:GetPartition"
                  - "glue:GetPartitions"
                  - "glue:CreatePartition"
                  - "glue:BatchCreatePartition"
                  - "glue:GetUserDefinedFunctions"
                Resource: "*"
      Path: "/"
      Description: 'EMR Serverless Execution Role with specific S3 and Glue permissions'

