name: AWS CLI Demo
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
run-name: aws cli demo -> ${{ github.actor }}
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The 777 job was automatically triggered by a ${{ github.event_name }} event."
      - run: aws sts get-caller-identity      
      - run: aws s3 ls

