name: AWS CLI Demo
run-name: aws cli demo -> ${{ github.actor }}
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The 777 job was automatically triggered by a ${{ github.event_name }} event."
      - run: aws s3 ls
