name: CDK Demo
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
run-name: CDK demo -> ${{ github.actor }}
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: aws sts get-caller-identity      
      - run: ls
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls
      - run: |
          cd handson
          ls
      - run: ls

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
        #   cache: "npm"

      - run: npm --version        
      - run: node --version
      - run: python --version


      # - name: Install dependencies
      #   run: npm install

      # - name: Install AWS CDK
      #   run: npm i -g aws-cdk      
